name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build kexts
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Goldfish64/MacPPCKernelSDK
          path: MacPPCKernelSDK

      - name: Darling and CI bootstrap
        run: |
          ./tools/install-darling.sh
          sudo apt -y install python3-lzss

      - name: map_fd bootstrap
        uses: robinraju/release-downloader@v1
        with:
          repository: bfleischer/map_fd
          tag: 'map_fd-1.0'
          fileName: 'map_fd-1.0.tbz'
          out-file-path: 'tools'

      - name: Xcode3 bootstrap
        uses: robinraju/release-downloader@v1
        with:
          repository: Goldfish64/xcode3-tools-ci
          tag: 'xcode3-packages'
          token: ${{ secrets.XCODE3_CI }}
          fileName: '*.pkg'
          out-file-path: 'tools'

      - name: Xcode3 install packages
        run: |
          cd tools
          sudo darling shell ./install-xcode-tools.sh
          cd ..

      - name: Build drivers
        run: make && make package

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
