name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build kexts
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Goldfish64/MacPPCKernelSDK
          path: MacPPCKernelSDK

      - name: Darling bootstrap
        run: ./tools/install-darling.sh

      - name: CI bootstrap prep
        uses: actions/checkout@v5
        with:
          repository: osx360/powerpc-kext-ci
          token: ${{ secrets.POWERPC_KEXT_CI }}
          fetch-depth: 1
          path: powerpc-kext-ci

      - name: Xcode3 bootstrap
        uses: robinraju/release-downloader@v1
        with:
          repository: osx360/powerpc-kext-ci
          tag: 'xcode3'
          token: ${{ secrets.POWERPC_KEXT_CI }}
          fileName: '*.tar.gz'
          out-file-path: 'powerpc-kext-ci/xcode-gcc'

      - name: CI bootstrap
        run: |
          cd powerpc-kext-ci
          sudo darling shell ./install-xcode-tools.sh
          sudo apt install python3-lzss
          cd ..

      - name: Build drivers
        run: make && make package

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
